# -*- coding: utf-8 -*-
"""Matrix Transpose.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hPNqh37w3GHJezbW3UYbG-5RaJcw-35R
"""

m=int(input('give me m'))
n=int(input('give me n'))
a1=[]
for iI in range(m):
    row=[]
    for j in range(n):
        row.append(int(input('give me a number')))
    a1.append(row)
    #return Matris
print(a1)

c=[]
for i in range(len(a1[0])):
     temp=[]
     for j in range(len(a1)):
         temp.append(a1[j][i])
     c.append(temp)
print(c)